checkpoint_path: /home/liujingqi/wanAR/LTX-2/ckpts/ltx-2-19b-dev.safetensors
gemma_path: /home/liujingqi/wanAR/LTX-2/ckpts/gemma3
model_name: ltx2_av
generator_grad:
  model: true
real_score_grad:
  model: false
fake_score_grad:
  model: true
denoising_step_list:
- 1000
- 757
- 522
- 0
num_train_timestep: 1000
real_video_guidance_scale: 3.0
real_audio_guidance_scale: 5.0
generator_task: bidirectional_av
real_task_type: bidirectional_av
fake_task_type: bidirectional_av
denoising_loss_type: velocity
distillation_loss: dmd
dmd_latent_mode: direct_noise
mixed_precision: true
gradient_checkpointing: true
batch_size: 4
lr: 2.0e-05
generator_lr: 2.0e-05
critic_lr: 2.0e-05
beta1: 0.9
beta2: 0.999
weight_decay: 0.01
dfake_gen_update_ratio: 5
max_grad_norm: 3.0
scheduler_type: constant
data_path: /home/liujingqi/wanAR/OmniForcing/LTX-2/packages/ltx-distillation/configs/mtv_merged.txt
backward_simulation: true
negative_prompt: blurry, out of focus, overexposed, underexposed, low contrast, washed out colors, excessive noise, grainy texture, poor lighting, flickering, motion blur, distorted proportions, unnatural skin tones, deformed facial features, asymmetrical face, missing facial features, extra limbs, disfigured hands, wrong hand count, artifacts around text, inconsistent perspective, camera shake, incorrect depth of field, background too sharp, background clutter, distracting reflections, harsh shadows, inconsistent lighting direction, color banding, cartoonish rendering, 3D CGI look, unrealistic materials, uncanny valley effect, incorrect ethnicity, wrong gender, exaggerated expressions, wrong gaze direction, mismatched lip sync, silent or muted audio, distorted voice, robotic voice, echo, background noise, off-sync audio, incorrect dialogue, added dialogue, repetitive speech, jittery movement, awkward pauses, incorrect timing, unnatural transitions, inconsistent framing, tilted camera, flat lighting, inconsistent tone, cinematic oversaturation, stylized filters, or AI artifacts.
num_frames: 121
video_height: 512
video_width: 768
sharding_strategy: hybrid_full
split_teacher_worker: true
teacher_num_nodes: 1
worker_num_nodes_per_group: 1
generator_fsdp_wrap_strategy: size
real_score_fsdp_wrap_strategy: size
fake_score_fsdp_wrap_strategy: size
text_encoder_fsdp_wrap_strategy: size
output_path: ./outputs/stage1_bidirectional_dmd_split_teacher_worker
log_iters: 100
wandb_project: OmniForcing
wandb_entity: lanpinggai697-peking-university
wandb_name: stage1_bidirectional_dmd_split_teacher_worker_resume_0402_103322
seed: 42
benchmark_enabled: false
benchmark_iters: 50
benchmark_num_prompts: 8
benchmark_seed: 12345
benchmark_video_fps: 24
benchmark_audio_sample_rate: 24000
no_save: false
no_visualize: true
resume_checkpoint: /home/liujingqi/wanAR/OmniForcing/LTX-2/packages/ltx-distillation/outputs/stage1_bidirectional_dmd_split_teacher_worker/0402_103322_stage1_bidirectional_dmd_split_teacher_worker/checkpoint_001000/model.pt
